### ISSUE TITLE
VS Code version compatibility

### ISSUE THREAD

**Issue by jkcts** [koszti/sqltools-snowflake-driver#1]
Is this driver specific to certain versions of VS Code? If yes, please let us know from which version upwards the driver works. 
While trying to install on **Version: 1.37.1 (system setup)** we get a compatibility error message. 

![image](https://user-images.githubusercontent.com/73902898/98017400-cf153080-1dc4-11eb-860f-dc63947f60b7.png)

**Comment by koszti** [comment]
VSCode 1.42.1 should be enough for this extension but it's tested only on the latest vscode 1.50.1

Upgrading from 1.37.1 sounds like wise idea anyways because is almost 1.5 years old. Enabling automatic updates in VS Code usually does a nice job and highly recommended to enable if possible.
