### ISSUE TITLE
Test connection fails when QUOTED_IDENTIFIERS_IGNORE_CASE is set to true

### ISSUE THREAD

**Issue by yadavsahil197** [koszti/sqltools-snowflake-driver#10]
The driver fails to connect for cases where the QUOTED_IDENTIFIERS_IGNORE_CASE in the snowflake account/user is set to True.
To handle all cases, we should set it to False for the session by adding this query
`ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE=FALSE;`

**Comment by koszti** [comment]
fixed in v0.2.1 and released to [vs marketplace](https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools).

It's now should be available in your vscode to upgrade.
