### ISSUE TITLE
externalbrowser authenticator for SSO

### ISSUE THREAD

**Issue by bharathjs93** [koszti/sqltools-snowflake-driver#13]
Hello, 
I'd like to know any plans about implementing external browser authenticator for SSO.

**Comment by koszti** [comment]
There are plans adding it, but it highly depends on when externalbrowser authentication feature will be available in the upstream [snowflake-nodejs-connector](https://github.com/snowflakedb/snowflake-connector-nodejs) driver.

Good news is that last week [this PR](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/140) added external browser authentication to the nodejs connector. We need to wait until snowflake officially releasing the new driver but at the same time we can start testing and developing it.

**Comment by yapnel** [comment]
I am also awaiting for this feature too

**Comment by koszti** [comment]
I created a new [auth-externalbrowser-sso](https://github.com/koszti/sqltools-snowflake-driver/tree/auth-externalbrowser-sso) branch and added [this commit](https://github.com/koszti/sqltools-snowflake-driver/commit/5f5eb61ffefc6fd99e2ca7dc3af5651d42039a38) to test the unreleased [SSO authenticator](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/140) feature of the upstream snowflake nodejs connector. Unfortunately I receive this error:
```
390133: SAML response is invalid or matching user is not found. Contact your local system administrator.
```
My snowflake instance is using OKTA, I'm sure it's configured it well and it's working fine with other snowflake clients.

This might be a bug in the the SSO feature of the upstream nodejs driver. It's also possible that it doesn't like OKTA but working fine with other Identity Providers. I think we need to wait until SSO support will be documented and released officially by Snowflake.


Repo: https://github.com/snowflakedb/snowflake-connector-nodejs
Documentation: https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html

**Comment by yapnel** [comment]
Hi the latest 1.6 version is out. No info of what is released. Are you able to test it please?

**Comment by koszti** [comment]
Thanks, it's promising and I started working on it. It requires to bump the snowflake-sdk in the upstream snowflake-promise package first. I sent PR at https://github.com/natesilva/snowflake-promise/pull/8 and hopefully will be merged very soon.

**Comment by koszti** [comment]
tested locally and browser based SSO is working with the latest snowflake sdk package. To support it properly in the SQL client we need to make another a small change in the snowflake-promise package again. PR sent to https://github.com/natesilva/snowflake-promise/pull/9.

**Comment by koszti** [comment]
New version with browser based SSO auth (0.4.0) is published to [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools) and it's ready to upgrade.
