### ISSUE TITLE
Connecting gives a 'cannot get database list' message

### ISSUE THREAD

**Issue by johanvanderkooij** [koszti/sqltools-snowflake-driver#3]
When setting up a connection from VSCode with Snowflake, the password validation passes (at least when typing a wrong password, it is explicitely mentioned that the password is wrong). I get the error message: cannot get database list. In the Snowflake query history, I cannot see any query being executed. Setting this up on another account, where I have SYSADMIN privileges, the connection is succesfull, I also can see al queries in the Snowflake query history window. What priviliges are required to set up the connection?

**Comment by koszti** [comment]
Is the database name correct in the connection form?

The test connection button runs two queries (source code [here](https://github.com/koszti/sqltools-snowflake-driver/blob/1577bb506b1d7b709065c8a5e1e0a1e11a86f68b/src/ls/driver.ts#L108)):
```
SHOW DATABASES;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE UPPER("name") = UPPER('<DBNAME_IN_CONN_FORM>');
```
If this returns zero row, then you see the ` cannot get database list` error. What can you see as output when you run the above two queries when you login to the snowflake UI as SYSADMIN?

**Comment by koszti** [comment]
Another idea. Does the `SYSADMIN` user has a default warehouse?

If not then can you please try to fill the warehouse in the connection from and click test connection again? I think we need to make the warehouse field mandatory.

**Comment by koszti** [comment]
I've published a new snowflake driver (0.2.0) to vs marketplace that makes the warehouse connection parameter mandatory and hopefully fixes your issue.

Can you please update the driver in your vscode and try again?

**Comment by johanvanderkooij** [comment]
does VSCode automatically install updates for extensions ? I see that it is om 0.2.0 now ?

it is working now, thanks for the update

**Comment by koszti** [comment]
> does VSCode automatically install updates for extensions ? I see that it is om 0.2.0 now ?

depends on the vscode settings, but AFAIK automatic update of extensions is enabled by default
