### ISSUE TITLE
Cannot get schema if database have hyphen

### ISSUE THREAD

**Issue by KreizIT** [koszti/sqltools-snowflake-driver#31]
When trying to develop Schemas node, we get an error : 'sqltools.getChildrenForTreeItem' failed.
Query in snowflake is : 
```
SELECT schema_name as "label", schema_name as "schema", 'connection.schema' as "type", 'group-by-ref-type' as "iconId", catalog_name as "database"
FROM DATA-DEV.information_schema.schemata
WHERE schema_name != 'INFORMATION_SCHEMA' AND catalog_name = UPPER('DATA-DEV')
ORDER BY 2

```
This error is due to database name : DATA-DEV. In that case database name must be enclosed by double quote.

**Comment by koszti** [comment]
thanks for reporting this.

New version (0.4.2) with the fix is published to [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools) and it should be now ready to upgrade in your VSCode.

**Comment by KreizIT** [comment]
Hello,
Not working. It's worth :D 
[1616567602620] INFO  (ls): Connection instance created for data-dev.
    ns: "conn-manager"
[1616567605287] ERROR (ls): Connecting error: {"code":-1,"data":{"driver":"Snowflake","driverOptions":{}},"name":"DecoratedException"}
    ns: "conn-manager"
[1616567605286] ERROR (ext): ERROR: Error opening connection Cannot find data-dev database, {"code":-1,"data":{"driver":"Snowflake","driverOptions":{}}}
    ns: "error-handler"
