### ISSUE TITLE
Cannot create a connection that requires a private key

### ISSUE THREAD

**Issue by austinkeller** [koszti/sqltools-snowflake-driver#8]

**Comment by koszti** [comment]
The [Snowflake NodeJS Connector](https://github.com/snowflakedb/snowflake-connector-python) unfortunately doesn't support [Key Pair Authentication](https://docs.snowflake.com/en/user-guide/key-pair-auth.html). We need to wait until it will be supported and documented by the Snowflake NodeJS Connector.

Repo: https://github.com/snowflakedb/snowflake-connector-nodejs
Documentation: https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html

**Comment by koszti** [comment]
snowflake added keypair/oauth authenticators to the nodejs driver this week by [this commit](https://github.com/snowflakedb/snowflake-connector-nodejs/commit/5c416d9946154b57edbbeef5330076cb1c79f889).

This is a great news however snowflake has not been released it yet. Hopefully they will document and support it officially soon and we can add it into the vscode plugin.

**Comment by koszti** [comment]
New version with Key Pair auth (0.4.0) is published to [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools) and it's ready to upgrade.
