### ISSUE TITLE
Keep on getting Network Error 

### ISSUE THREAD

**Issue by FanliZhou860815** [koszti/sqltools-snowflake-driver#9]
Keep on receiving this ERROR: Error opening connection Network error. Could not reach Snowflake., {"code":401001,"data":{"driver":"Snowflake","driverOptions":{}}}  when trying to connect to Snowflake.  Same connection setting works on Snowflake UI and other SQL tools on the same machine.  Could anyone help please ? Thanks in advance !

**Comment by WoggyG** [comment]
I have the same error however i can connect to  Snowflake with other IDEs

[1608073630196] ERROR (ls): Connecting error: {"code":401001,"data":{"driver":"Snowflake","driverOptions":{}},"name":"NetworkError"}
    ns: "conn-manager"
[1608073630197] ERROR (ext): ERROR: Error opening connection Network error. Could not reach Snowflake., {"code":401001,"data":{"driver":"Snowflake","driverOptions":{}}}
    ns: "error-handler"

**Comment by WoggyG** [comment]
managed to solve it 

the trick is in the snowflake account name. it has to look like this 

<accountname>.ap-southeast-2

or 

follow the table here : https://docs.snowflake.com/en/user-guide/connecting.html#your-snowflake-account-name

**Comment by FanliZhou860815** [comment]
It works! Thank you very much @WoggyG ！
